import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildServer } from "../../apps/core/src/server.js";
import type { NovaCoreConfig } from "../../apps/core/src/config.js";

describe("bootstrap golden flow", () => {
  let tempDir: string;
  let app: Awaited<ReturnType<typeof buildServer>>["app"];

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "nova-bootstrap-test-"));
    const config: NovaCoreConfig = {
      pipePath: "\\\\.\\pipe\\nova-bootstrap-test",
      authToken: "bootstrap-token",
      profileRoot: tempDir,
      auditFilePath: path.join(tempDir, "audit", "timeline.jsonl"),
      memoryRootPath: path.join(tempDir, "memory"),
      allowInstallCommands: false
    };
    app = (await buildServer(config)).app;
  });

  afterEach(async () => {
    await app.close();
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("creates scaffold files when write step is approved", async () => {
    const dryRun = await app.inject({
      method: "POST",
      url: "/bootstrap/create",
      headers: { "x-nova-token": "bootstrap-token" },
      payload: {
        brief: "Create a project called Rocket",
        targetDirectory: tempDir,
        mode: "dry-run"
      }
    });
    expect(dryRun.statusCode).toBe(200);
    const dryRunBody = dryRun.json();
    const approvedActionIds = dryRunBody.audit.steps.map((step: { stepId: string }) => step.stepId);

    const execute = await app.inject({
      method: "POST",
      url: "/bootstrap/create",
      headers: { "x-nova-token": "bootstrap-token" },
      payload: {
        brief: "Create a project called Rocket",
        targetDirectory: tempDir,
        mode: "execute",
        approvedActionIds,
        approver: "test-user"
      }
    });
    expect(execute.statusCode).toBe(200);
    const executeBody = execute.json();
    expect(executeBody.filesWritten).toBeGreaterThan(10);

    const readme = await fs.readFile(path.join(tempDir, "rocket", "README.md"), "utf-8");
    expect(readme).toContain("Generated by Nova bootstrap");
  });
});

