from __future__ import annotations

import re
from pathlib import Path

from .models import ActionStep, BootstrapFeatures, BootstrapSpec


DEFAULT_PROJECT_NAME = "nova-generated-app"


def infer_bootstrap_spec_from_brief(brief: str, target_directory: str) -> BootstrapSpec:
    inferred_name = extract_project_name(brief) or (
        "nova-service" if "api" in brief.lower() else DEFAULT_PROJECT_NAME
    )
    project_name = sanitize_project_name(inferred_name)
    spec = BootstrapSpec(
        projectName=project_name,
        targetDirectory=str(Path(target_directory).resolve()),
        description=brief,
        packageManager="pnpm",
        stack="ts-fullstack-default",
        features=BootstrapFeatures(
            web=True,
            api=True,
            worker=True,
            postgres=True,
            redis=True,
            docker=True,
            githubActions=True,
        ),
    )
    validation = validate_bootstrap_spec(spec)
    if validation:
        raise ValueError(f"Invalid bootstrap spec: {validation}")
    return spec


def validate_bootstrap_spec(spec: BootstrapSpec) -> list[str]:
    errors: list[str] = []
    if not re.match(r"^[a-z0-9][a-z0-9-]*$", spec.projectName):
        errors.append("projectName must be slug-like (letters, numbers, hyphens).")
    if not spec.targetDirectory.strip():
        errors.append("targetDirectory is required.")
    if spec.packageManager != "pnpm":
        errors.append("Only pnpm is supported in Nova v1.")
    if spec.stack == "ts-fullstack-default":
        if not (spec.features.web and spec.features.api and spec.features.worker):
            errors.append("Default stack requires web, api, and worker.")
        if not (spec.features.postgres and spec.features.redis):
            errors.append("Default stack requires postgres and redis.")
    return errors


def plan_bootstrap_actions(spec: BootstrapSpec) -> list[ActionStep]:
    target_root = Path(spec.targetDirectory) / spec.projectName
    return [
        ActionStep(
            id="bootstrap-create-root",
            title="Create project root",
            description=f"Create scaffold root at {target_root}.",
            kind="write",
            risk="high",
            requiresApproval=True,
            dryRunPreview=f"mkdir {target_root}",
        ),
        ActionStep(
            id="bootstrap-write-files",
            title="Write project files",
            description=(
                "Generate Next.js web app, Fastify API, BullMQ worker, Docker Compose, CI, env templates, and docs."
            ),
            kind="bootstrap",
            risk="high",
            requiresApproval=True,
            dryRunPreview="write production-ready monorepo scaffold",
        ),
        ActionStep(
            id="bootstrap-install",
            title="Install dependencies",
            description="Install workspace dependencies with pnpm.",
            kind="install",
            risk="high",
            requiresApproval=True,
            command="pnpm",
            args=["install"],
            workingDirectory=str(target_root),
            dryRunPreview=f"cd {target_root} && pnpm install",
        ),
    ]


def materialize_bootstrap_files(spec: BootstrapSpec) -> dict[str, str]:
    root = spec.projectName
    return {
        f"{root}/README.md": f"# {spec.projectName}\n\nGenerated by Nova (Python core).\n",
        f"{root}/.gitignore": "node_modules/\ndist/\n.env\n.next/\n",
        f"{root}/pnpm-workspace.yaml": 'packages:\n  - "apps/*"\n  - "packages/*"\n',
        f"{root}/package.json": """{
  "name": "%s",
  "private": true,
  "packageManager": "pnpm@10.8.1",
  "scripts": {
    "dev": "pnpm --parallel --filter @nova/web --filter @nova/api --filter @nova/worker dev",
    "dev:infra": "docker compose up -d",
    "build": "pnpm -r --if-present build",
    "lint": "pnpm -r --if-present lint",
    "test": "pnpm -r --if-present test",
    "check": "pnpm lint && pnpm test && pnpm build"
  }
}
"""
        % spec.projectName,
        f"{root}/docker-compose.yml": """version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nova
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
""",
        f"{root}/apps/web/package.json": """{
  "name": "@nova/web",
  "private": true,
  "scripts": {
    "dev": "next dev -p ${WEB_PORT:-3000}",
    "build": "next build",
    "start": "next start -p ${WEB_PORT:-3000}",
    "lint": "next lint",
    "test": "echo \\"no web tests yet\\""
  },
  "dependencies": {
    "next": "^15.3.0",
    "react": "^19.1.0",
    "react-dom": "^19.1.0"
  }
}
""",
        f"{root}/apps/web/app/page.tsx": """export default function Page() {
  return (
    <main>
      <h1>Nova scaffold ready</h1>
      <p>Web + API + Worker generated by Nova.</p>
    </main>
  );
}
""",
        f"{root}/apps/api/package.json": """{
  "name": "@nova/api",
  "private": true,
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "build": "tsc -p tsconfig.json",
    "start": "node dist/index.js",
    "lint": "tsc -p tsconfig.json --noEmit",
    "test": "echo \\"no api tests yet\\""
  },
  "dependencies": {
    "fastify": "^5.6.0",
    "bullmq": "^5.58.0",
    "ioredis": "^5.7.0"
  }
}
""",
        f"{root}/apps/api/src/index.ts": """import Fastify from "fastify";
const app = Fastify({ logger: true });
const port = Number(process.env.API_PORT ?? 4000);
app.get("/health", async () => ({ ok: true }));
app.listen({ port, host: "0.0.0.0" });
""",
        f"{root}/apps/worker/package.json": """{
  "name": "@nova/worker",
  "private": true,
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "build": "tsc -p tsconfig.json",
    "start": "node dist/index.js",
    "lint": "tsc -p tsconfig.json --noEmit",
    "test": "echo \\"no worker tests yet\\""
  },
  "dependencies": {
    "bullmq": "^5.58.0",
    "ioredis": "^5.7.0"
  }
}
""",
        f"{root}/apps/worker/src/index.ts": """import { Worker } from "bullmq";
new Worker("nova-jobs", async (job) => ({ ok: true, id: job.id }), {
  connection: { host: "127.0.0.1", port: 6379 }
});
""",
        f"{root}/docs/architecture.md": (
            "# Architecture\n\n"
            f"- Project: {spec.projectName}\n"
            "- Services: apps/web, apps/api, apps/worker\n"
        ),
        f"{root}/.github/workflows/ci.yml": """name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
""",
    }


def extract_project_name(brief: str) -> str | None:
    quoted = re.search(r'(?:called|named)\s+["\']([^"\']+)["\']', brief, flags=re.I)
    if quoted:
        return quoted.group(1)
    plain = re.search(r"(?:called|named)\s+([a-zA-Z0-9-_]+)", brief, flags=re.I)
    return plain.group(1) if plain else None


def sanitize_project_name(name: str) -> str:
    normalized = re.sub(r"[^a-z0-9-]+", "-", name.strip().lower())
    normalized = re.sub(r"^-+|-+$", "", normalized)
    return normalized or DEFAULT_PROJECT_NAME

