import path from "node:path";
import type { ActionStep, BootstrapSpec } from "@nova/contracts";

const DEFAULT_PROJECT_NAME = "nova-generated-app";

export function inferBootstrapSpecFromBrief(
  brief: string,
  targetDirectory: string
): BootstrapSpec {
  const sanitized = brief.toLowerCase();
  const projectName =
    extractProjectName(brief) ??
    (sanitized.includes("api") ? "nova-service" : DEFAULT_PROJECT_NAME);

  return {
    projectName,
    targetDirectory,
    description: brief,
    packageManager: "pnpm",
    stack: "ts-fullstack-default",
    features: {
      web: true,
      api: true,
      worker: true,
      postgres: true,
      redis: true,
      docker: true,
      githubActions: true
    }
  };
}

export function planBootstrapActions(spec: BootstrapSpec): ActionStep[] {
  const targetRoot = path.join(spec.targetDirectory, spec.projectName);
  return [
    {
      id: "bootstrap-create-root",
      title: "Create project root",
      description: `Create scaffold root at ${targetRoot}.`,
      kind: "write",
      risk: "high",
      requiresApproval: true,
      dryRunPreview: `mkdir ${targetRoot}`
    },
    {
      id: "bootstrap-write-files",
      title: "Write project files",
      description:
        "Generate web/api/worker apps, Docker Compose, CI workflow, env templates, and docs.",
      kind: "bootstrap",
      risk: "high",
      requiresApproval: true,
      dryRunPreview: "write ~30 scaffold files"
    },
    {
      id: "bootstrap-install",
      title: "Install dependencies",
      description: "Install workspace dependencies with pnpm.",
      kind: "install",
      risk: "high",
      requiresApproval: true,
      command: "pnpm",
      args: ["install"],
      dryRunPreview: "pnpm install"
    }
  ];
}

export function materializeBootstrapFiles(
  spec: BootstrapSpec
): Record<string, string> {
  const root = spec.projectName;
  const files: Record<string, string> = {
    [`${root}/.gitignore`]: scaffoldGitignore(),
    [`${root}/README.md`]: scaffoldReadme(spec),
    [`${root}/pnpm-workspace.yaml`]: scaffoldPnpmWorkspace(),
    [`${root}/package.json`]: scaffoldRootPackageJson(spec),
    [`${root}/tsconfig.base.json`]: scaffoldTsconfigBase(),
    [`${root}/.env.example`]: scaffoldEnvExample(),
    [`${root}/docker-compose.yml`]: scaffoldDockerCompose(),
    [`${root}/.github/workflows/ci.yml`]: scaffoldCiWorkflow(),
    [`${root}/apps/web/package.json`]: scaffoldWebPackageJson(),
    [`${root}/apps/web/next.config.mjs`]: scaffoldWebNextConfig(),
    [`${root}/apps/web/tsconfig.json`]: scaffoldWebTsconfig(),
    [`${root}/apps/web/app/layout.tsx`]: scaffoldWebLayout(),
    [`${root}/apps/web/app/page.tsx`]: scaffoldWebPage(),
    [`${root}/apps/api/package.json`]: scaffoldApiPackageJson(),
    [`${root}/apps/api/tsconfig.json`]: scaffoldApiTsconfig(),
    [`${root}/apps/api/src/index.ts`]: scaffoldApiEntry(),
    [`${root}/apps/worker/package.json`]: scaffoldWorkerPackageJson(),
    [`${root}/apps/worker/tsconfig.json`]: scaffoldWorkerTsconfig(),
    [`${root}/apps/worker/src/index.ts`]: scaffoldWorkerEntry(),
    [`${root}/packages/shared/package.json`]: scaffoldSharedPackageJson(),
    [`${root}/packages/shared/tsconfig.json`]: scaffoldSharedTsconfig(),
    [`${root}/packages/shared/src/index.ts`]: scaffoldSharedEntry(),
    [`${root}/docs/architecture.md`]: scaffoldArchitectureDoc(spec)
  };

  return files;
}

function extractProjectName(brief: string): string | undefined {
  const match = brief.match(/(?:called|named)\s+([a-zA-Z0-9-_]+)/i);
  if (!match) {
    return undefined;
  }
  return match[1].toLowerCase().replace(/[^a-z0-9-_]/g, "");
}

function scaffoldGitignore(): string {
  return `node_modules/
dist/
.env
.env.local
.next/
coverage/
`;
}

function scaffoldReadme(spec: BootstrapSpec): string {
  return `# ${spec.projectName}

Generated by Nova bootstrap.

## Stack

- Web: Next.js (TypeScript)
- API: Fastify
- Worker: BullMQ
- Infra: PostgreSQL + Redis via Docker Compose
- CI: GitHub Actions
- Package manager: pnpm

## Quick Start

\`\`\`bash
pnpm install
docker compose up -d
pnpm dev
\`\`\`
`;
}

function scaffoldPnpmWorkspace(): string {
  return `packages:
  - "apps/*"
  - "packages/*"
`;
}

function scaffoldRootPackageJson(spec: BootstrapSpec): string {
  return JSON.stringify(
    {
      name: spec.projectName,
      private: true,
      packageManager: "pnpm@10.8.1",
      scripts: {
        dev: "pnpm -r --parallel dev",
        build: "pnpm -r build",
        test: "pnpm -r test",
        lint: "pnpm -r lint"
      }
    },
    null,
    2
  );
}

function scaffoldTsconfigBase(): string {
  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  }
}
`;
}

function scaffoldEnvExample(): string {
  return `DATABASE_URL=postgres://postgres:postgres@localhost:5432/nova
REDIS_URL=redis://localhost:6379
PORT=4000
`;
}

function scaffoldDockerCompose(): string {
  return `version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nova
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
`;
}

function scaffoldCiWorkflow(): string {
  return `name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm build
      - run: pnpm test
`;
}

function scaffoldWebPackageJson(): string {
  return JSON.stringify(
    {
      name: "@app/web",
      private: true,
      scripts: {
        dev: "next dev -p 3000",
        build: "next build",
        start: "next start -p 3000",
        lint: "next lint",
        test: "echo \"no web tests yet\""
      },
      dependencies: {
        next: "^15.3.0",
        react: "^19.1.0",
        "react-dom": "^19.1.0"
      },
      devDependencies: {
        typescript: "^5.9.2",
        "@types/react": "^19.1.3",
        "@types/node": "^24.5.2"
      }
    },
    null,
    2
  );
}

function scaffoldWebNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true
};

export default nextConfig;
`;
}

function scaffoldWebTsconfig(): string {
  return `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "lib": ["dom", "es2022"],
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["**/*.ts", "**/*.tsx"]
}
`;
}

function scaffoldWebLayout(): string {
  return `import type { Metadata } from "next";
import "./styles.css";

export const metadata: Metadata = {
  title: "Nova Web",
  description: "Generated by Nova"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function scaffoldWebPage(): string {
  return `export default function Page() {
  return (
    <main style={{ padding: "3rem", fontFamily: "Segoe UI, sans-serif" }}>
      <h1>Nova Scaffold Ready</h1>
      <p>Your web, API, and worker services are wired as a workspace.</p>
    </main>
  );
}
`;
}

function scaffoldApiPackageJson(): string {
  return JSON.stringify(
    {
      name: "@app/api",
      private: true,
      scripts: {
        dev: "tsx watch src/index.ts",
        build: "tsc -p tsconfig.json",
        start: "node dist/index.js",
        test: "echo \"no api tests yet\"",
        lint: "tsc -p tsconfig.json --noEmit"
      },
      dependencies: {
        fastify: "^5.6.0"
      },
      devDependencies: {
        tsx: "^4.20.5",
        typescript: "^5.9.2",
        "@types/node": "^24.5.2"
      }
    },
    null,
    2
  );
}

function scaffoldApiTsconfig(): string {
  return `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
`;
}

function scaffoldApiEntry(): string {
  return `import Fastify from "fastify";

const app = Fastify({ logger: true });
const port = Number(process.env.PORT ?? 4000);

app.get("/health", async () => ({ ok: true }));

app.listen({ port, host: "0.0.0.0" }).catch((error) => {
  app.log.error(error);
  process.exit(1);
});
`;
}

function scaffoldWorkerPackageJson(): string {
  return JSON.stringify(
    {
      name: "@app/worker",
      private: true,
      scripts: {
        dev: "tsx watch src/index.ts",
        build: "tsc -p tsconfig.json",
        start: "node dist/index.js",
        test: "echo \"no worker tests yet\"",
        lint: "tsc -p tsconfig.json --noEmit"
      },
      dependencies: {
        bullmq: "^5.58.0",
        ioredis: "^5.7.0"
      },
      devDependencies: {
        tsx: "^4.20.5",
        typescript: "^5.9.2",
        "@types/node": "^24.5.2"
      }
    },
    null,
    2
  );
}

function scaffoldWorkerTsconfig(): string {
  return `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
`;
}

function scaffoldWorkerEntry(): string {
  return `import { Queue, Worker } from "bullmq";

const redisConnection = {
  host: process.env.REDIS_HOST ?? "127.0.0.1",
  port: Number(process.env.REDIS_PORT ?? 6379)
};

const queue = new Queue("jobs", { connection: redisConnection });

const worker = new Worker(
  "jobs",
  async (job) => {
    console.log("Processing job", job.id, job.data);
    return { processed: true };
  },
  { connection: redisConnection }
);

worker.on("completed", (job) => {
  console.log("Completed job", job.id);
});

await queue.add("warmup", { createdAt: new Date().toISOString() });
`;
}

function scaffoldSharedPackageJson(): string {
  return JSON.stringify(
    {
      name: "@app/shared",
      private: true,
      main: "dist/index.js",
      types: "dist/index.d.ts",
      scripts: {
        build: "tsc -p tsconfig.json",
        lint: "tsc -p tsconfig.json --noEmit",
        test: "echo \"no shared tests yet\""
      },
      devDependencies: {
        typescript: "^5.9.2"
      }
    },
    null,
    2
  );
}

function scaffoldSharedTsconfig(): string {
  return `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*.ts"]
}
`;
}

function scaffoldSharedEntry(): string {
  return `export interface HealthStatus {
  ok: boolean;
  service: string;
}
`;
}

function scaffoldArchitectureDoc(spec: BootstrapSpec): string {
  return `# Architecture

This repository was generated by Nova.

## Project
- Name: ${spec.projectName}
- Stack: ${spec.stack}
- Generated: ${new Date().toISOString()}

## Services
- \`apps/web\`: Next.js frontend
- \`apps/api\`: Fastify API
- \`apps/worker\`: BullMQ worker
- \`packages/shared\`: shared contracts/utilities
`;
}

