import { describe, expect, it } from "vitest";
import {
  inferBootstrapSpecFromBrief,
  materializeBootstrapFiles,
  planBootstrapActions,
  validateBootstrapSpec
} from "../../packages/bootstrap/src/index.js";

describe("bootstrap spec validation", () => {
  it("builds default TS fullstack spec", () => {
    const spec = inferBootstrapSpecFromBrief(
      "Create a production-ready app called NovaStack",
      "C:/tmp"
    );
    expect(spec.stack).toBe("ts-fullstack-default");
    expect(spec.features.web).toBe(true);
    expect(spec.features.api).toBe(true);
    expect(spec.features.worker).toBe(true);
  });

  it("plans high-risk mutating actions", () => {
    const spec = inferBootstrapSpecFromBrief("scaffold a new service", "C:/tmp");
    const steps = planBootstrapActions(spec);
    expect(steps.some((step) => step.requiresApproval)).toBe(true);
    expect(steps.some((step) => step.kind === "install")).toBe(true);
    const installStep = steps.find((step) => step.kind === "install");
    expect(installStep?.workingDirectory).toContain(spec.projectName);
  });

  it("materializes expected scaffold files", () => {
    const spec = inferBootstrapSpecFromBrief("bootstrap project called Orbit", "C:/tmp");
    const files = materializeBootstrapFiles(spec);
    expect(files["orbit/README.md"]).toContain("Generated by Nova bootstrap");
    expect(files["orbit/apps/api/src/index.ts"]).toContain("Fastify");
    expect(files["orbit/apps/web/app/globals.css"]).toContain(".page");
    expect(files["orbit/docker-compose.yml"]).toContain("postgres");
    expect(files["orbit/.github/workflows/ci.yml"]).toContain("pnpm lint");
  });

  it("rejects invalid bootstrap spec", () => {
    const validation = validateBootstrapSpec({
      projectName: "invalid name",
      targetDirectory: "",
      packageManager: "pnpm",
      stack: "ts-fullstack-default",
      features: {
        web: false,
        api: true,
        worker: true,
        postgres: true,
        redis: true,
        docker: true,
        githubActions: true
      }
    });

    expect(validation.valid).toBe(false);
    expect(validation.errors.length).toBeGreaterThan(0);
  });
});

